table dCalendario
	lineageTag: d0f08583-5ff8-48fa-9ba6-248fcfe3fa06

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: b703f4df-11f4-40c8-9fd2-17ee7d7d637c
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 284ec98f-1ef2-49cf-9037-3e72795960e8
			defaultHierarchy: LocalDateTable_808ade0b-164e-4ae4-ab9d-f264ccd6893d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: d5b30591-3bbb-4610-8b4d-7bf3daac84c1
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Mês Num'
		dataType: int64
		formatString: 0
		lineageTag: a00a2dbe-f7a9-4ff5-a29b-c34b767224bd
		summarizeBy: sum
		sourceColumn: Mês Num

		annotation SummarizationSetBy = Automatic

	column 'Nome Mês'
		dataType: string
		lineageTag: a991a7cc-07b1-48c1-982a-d90e75931d31
		summarizeBy: none
		sourceColumn: Nome Mês

		annotation SummarizationSetBy = Automatic

	column Mês/Ano
		dataType: string
		lineageTag: 78b50149-a311-4aac-ae81-7d88a11070ba
		summarizeBy: none
		sourceColumn: Mês/Ano

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: ac6efa88-7ee5-40c1-b14c-2ef11a39d4bf
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: string
		lineageTag: f07c39aa-07d5-453c-bd0b-a84189559507
		summarizeBy: none
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana'
		dataType: string
		lineageTag: c9145a35-0b99-4e2e-b56f-c5c1c4f28ecd
		summarizeBy: none
		sourceColumn: Dia da Semana

		annotation SummarizationSetBy = Automatic

	column AnoMêsInt
		dataType: int64
		formatString: 0
		lineageTag: 8693c877-aebd-4ba5-93b4-5fe700c1d3fe
		summarizeBy: sum
		sourceColumn: AnoMêsInt

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source = ```
				let
				    // 1. Define o intervalo de anos (ajuste se necessário)
				    DataInicial = #date(1890, 1, 1),
				    DataFinal = #date(2026, 12, 31),
				    
				    // 2. Calcula a quantidade de dias no intervalo
				    QtdeDias = Duration.Days(DataFinal - DataInicial) + 1,
				    
				    // 3. Gera a lista contínua de datas
				    ListaDatas = List.Dates(DataInicial, QtdeDias, #duration(1, 0, 0, 0)),
				    
				    // 4. Converte a lista em Tabela
				    Tabela = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}, null, ExtraValues.Error),
				    
				    // 5. Altera o tipo da coluna para Data
				    TipoData = Table.TransformColumnTypes(Tabela,{{"Data", type date}}),
				    
				    // 6. Adiciona colunas de contexto temporal
				    Ano = Table.AddColumn(TipoData, "Ano", each Date.Year([Data]), Int64.Type),
				    MesNum = Table.AddColumn(Ano, "Mês Num", each Date.Month([Data]), Int64.Type),
				    NomeMes = Table.AddColumn(MesNum, "Nome Mês", each Text.Start(Date.MonthName([Data]), 3), type text),
				    MesAno = Table.AddColumn(NomeMes, "Mês/Ano", each Text.Start(Date.MonthName([Data]), 3) & "/" & Text.From(Date.Year([Data])), type text),
				    Trimestre = Table.AddColumn(MesAno, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Data])), type text),
				    Semestre = Table.AddColumn(Trimestre, "Semestre", each "S" & (if Date.Month([Data]) <= 6 then "1" else "2"), type text),
				    DiaDaSemana = Table.AddColumn(Semestre, "Dia da Semana", each Text.Start(Date.DayOfWeekName([Data]), 3), type text),
				    AnoMesInt = Table.AddColumn(DiaDaSemana, "AnoMêsInt", each Date.Year([Data]) * 100 + Date.Month([Data]), Int64.Type)
				in
				    AnoMesInt
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

